// Cute, punny cat jokes the kitten says now and then.
export const JOKES = [
  'What do you call a pile of kittens? A meow-ntain!',
  'Why was the cat so good at video games? It had nine lives!',
  'What is a cat\'s favourite colour? Purr-ple!',
  'What do cats eat for breakfast? Mice Krispies!',
  'Why did the cat sit on the computer? To keep an eye on the mouse!',
  'What do you call a cat who loves to bowl? An alley cat!',
  'I\'m not lazy, I\'m in energy-saving meow-d.',
  'What\'s a cat\'s favourite subject? Hiss-tory!',
  'What do cats like to read? Cat-alogues!',
  'How do cats end a fight? They hiss and make up!',
  'Why don\'t cats play poker in the jungle? Too many cheetahs!',
  'What\'s a cat\'s favourite dessert? Chocolate mouse!',
  'What do you call a cat that gets anything it wants? Purr-suasive!',
  'Your Chinese is paw-some today!',
  'I\'ve cat to be the luckiest kitten ever.',
  'You\'ve got to be kitten me!',
  'Stay pawsitive — you can do it!',
  'What did the cat say when it lost all its money? I\'m paw!',
  'Why did the cat join the Red Cross? It wanted to be a first-aid kit!',
  'What do you call a cat at the beach on Christmas? Sandy Claws!',
  'What\'s a cat\'s favourite song? Three Blind Mice!',
  'I\'m feline fine, thank you for asking!',
  'Let\'s do some spelling — it\'ll be purr-fect!',
  'Why are cats good singers? They\'re very mew-sical!',
  'What do you call a cat that loves Chinese? A Mandarin-meow!',
  'Did you hear about the cat who swallowed a ball of wool? She had mittens!',
  'What happens when a cat eats a lemon? It becomes a sour puss!',
  'I would tell you a joke about my tail… but it\'s too long!',
  'How does a cat sing scales? Do-re-mew!',
  'What\'s my favourite button on the remote? Paws!',
];
export const randomJoke = (not) => { let j; do { j = JOKES[Math.floor(Math.random() * JOKES.length)]; } while (j === not && JOKES.length > 1); return j; };
